name = "MeshFreeExteriorCalculus"
uuid = "d05e753e-b5eb-49c2-b1f3-52333dc187ca"
version = "0.1.0"
authors = ["Craig M. Hamel <cmhamel32@gmail.com>"]

[deps]
Exodus = "f57ae99e-f805-4780-bdca-96e224be1e5a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Exodus = "0.14"
LinearAlgebra = "1"
SparseArrays = "1"
